server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置问价所在路径
  type-aliases-package: com.dlwlrma.pojo                 # 所有Pojo别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       #mapper映射文件

spring:
  application:
    name: spring-cloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource           # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver           # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud_db03              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                          # 数据库连接池的最小维持连接数
      initial-size: 5                                     # 初始化连接数
      max-total: 5                                        # 最大连接数
      max-wait-millis: 200                               # 等待连接获取的最大超时时间
logging:
  pattern:
    level: debug


#将 8001注册进Eureka 7001

eureka:
  client:  #客户端注册进eureka服务列表内
    service-url:
    #单机版
#      defaultZone: http://localhost:7001/eureka
    #集群版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
      instance-id: springcloud-dept8003   #自定义hystrix相关的服务名称信息
      prefer-ip-address: true  #访问路径可以显示ip地址


info:
  app.name: dlwlrma-springcloud
  company.name: www.dlwlrma.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

